# Generated by Django 4.1.1 on 2022-09-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_datecompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duedate',
            field=models.DateField(blank=True, default=None),
        ),
    ]
