# Generated by Django 4.1.1 on 2022-09-24 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_duedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='duedate',
        ),
    ]
