# Generated by Django 4.1.1 on 2022-09-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_task_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duedate',
            field=models.DateField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
